[[pages]]
path = "main.py"
name = "Data Explorer"
icon = "ğŸˆï¸ï¸"
is_section = false

[[pages]]
path = "other_pages/profile.py"
name = "Tutorial"
icon = ":books:"
is_section = false

[[pages]]
path = "other_pages/chat.py"
name = "Chat"
icon = ":arrow_up_small:"
is_section = false